"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.65899e+09:1.69251e+09]
Warning: empty y range [44:44], adjusting to [43.56:44.44]
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

[Tue Feb 07 06:31:58.409336 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213] [2023-02-07 06:31:58,394] ERROR in app: Exception on / [GET]
[Tue Feb 07 06:31:58.409550 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213] Traceback (most recent call last):
[Tue Feb 07 06:31:58.409596 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
[Tue Feb 07 06:31:58.409638 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213]     response = self.full_dispatch_request()
[Tue Feb 07 06:31:58.409677 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Tue Feb 07 06:31:58.409717 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213]     rv = self.handle_user_exception(e)
[Tue Feb 07 06:31:58.409754 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Tue Feb 07 06:31:58.409794 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213]     rv = self.dispatch_request()
[Tue Feb 07 06:31:58.409831 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
[Tue Feb 07 06:31:58.410001 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Tue Feb 07 06:31:58.410042 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213]   File "/var/www/basic-flask-app/app.py", line 32, in index
[Tue Feb 07 06:31:58.410081 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213]     create_cursor = connection.cursor()
[Tue Feb 07 06:31:58.410117 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213]   File "/usr/local/lib/python3.9/dist-packages/mysql/connector/connection.py", line 1406, in cursor
[Tue Feb 07 06:31:58.410155 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213]     raise OperationalError("MySQL Connection not available")
[Tue Feb 07 06:31:58.410192 2023] [wsgi:error] [pid 2056:tid 548316717440] [remote 192.168.1.222:65213] mysql.connector.errors.OperationalError: MySQL Connection not available
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [1:1], adjusting to [0.99:1.01]
[Tue Feb 07 07:10:00.207730 2023] [wsgi:error] [pid 2972:tid 547707253120] [remote 192.168.1.222:65281] File does not exist
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

[Tue Feb 07 07:10:24.607260 2023] [wsgi:error] [pid 2972:tid 547707253120] [remote 192.168.1.222:65282] File has been deleted
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [555:555], adjusting to [549.45:560.55]
[Tue Feb 07 07:10:26.137894 2023] [wsgi:error] [pid 2972:tid 547673682304] [remote 192.168.1.222:65282] File has been deleted
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [555:555], adjusting to [549.45:560.55]
[Tue Feb 07 07:10:45.363425 2023] [wsgi:error] [pid 2972:tid 547673682304] [remote 192.168.1.222:65283] File has been deleted
[Tue Feb 07 07:10:52.066546 2023] [wsgi:error] [pid 2972:tid 547707253120] [remote 192.168.1.222:65284] File has been deleted
[Tue Feb 07 07:11:05.966447 2023] [wsgi:error] [pid 2972:tid 547673682304] [remote 192.168.1.222:65285] File has been deleted
[Tue Feb 07 07:11:38.214466 2023] [wsgi:error] [pid 2972:tid 547673682304] [remote 192.168.1.222:65286] File has been deleted
[Tue Feb 07 07:11:48.359694 2023] [wsgi:error] [pid 2972:tid 547707253120] [remote 192.168.1.222:65287] File has been deleted
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: warning: Skipping data file with no valid points

plot "/var/www/basic-flask-app/moistureData.txt" using 1:2 with linespoints
                                                                           ^
"/var/www/basic-flask-app/gnuMoisturePlotScript" line 8: x range is invalid

[Tue Feb 07 07:15:03.418440 2023] [wsgi:error] [pid 3133:tid 547719516544] [remote 192.168.1.222:65291] File has been deleted
[Tue Feb 07 07:15:09.438076 2023] [wsgi:error] [pid 3133:tid 547711123840] [remote 192.168.1.222:65292] File does not exist
[Tue Feb 07 07:15:38.444936 2023] [wsgi:error] [pid 3133:tid 547719516544] [remote 192.168.1.222:65296] File does not exist
[Tue Feb 07 07:16:08.865791 2023] [wsgi:error] [pid 3133:tid 547711123840] [remote 192.168.1.222:65297] File has been deleted
[Tue Feb 07 07:18:43.816439 2023] [wsgi:error] [pid 3339:tid 547711705472] [remote 192.168.1.222:65310] File does not exist
Warning: empty x range [1.67575e+09:1.67575e+09], adjusting to [1.659e+09:1.69251e+09]
Warning: empty y range [555:555], adjusting to [549.45:560.55]
[Tue Feb 07 07:19:12.869280 2023] [wsgi:error] [pid 3339:tid 547678134656] [remote 192.168.1.222:65312] File has been deleted
Warning: empty x range [1.67578e+09:1.67578e+09], adjusting to [1.65902e+09:1.69254e+09]
Warning: empty y range [10:10], adjusting to [9.9:10.1]
[Tue Feb 07 15:18:11.890146 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517] [2023-02-07 15:18:11,814] ERROR in app: Exception on / [GET]
[Tue Feb 07 15:18:11.890371 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517] Traceback (most recent call last):
[Tue Feb 07 15:18:11.890415 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
[Tue Feb 07 15:18:11.890458 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]     response = self.full_dispatch_request()
[Tue Feb 07 15:18:11.890505 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Tue Feb 07 15:18:11.890547 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]     rv = self.handle_user_exception(e)
[Tue Feb 07 15:18:11.890586 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Tue Feb 07 15:18:11.890625 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]     rv = self.dispatch_request()
[Tue Feb 07 15:18:11.890663 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
[Tue Feb 07 15:18:11.890761 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Tue Feb 07 15:18:11.890801 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]   File "/var/www/basic-flask-app/app.py", line 36, in index
[Tue Feb 07 15:18:11.890839 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]     create_cursor.execute(gardenDataInsert)
[Tue Feb 07 15:18:11.890877 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]   File "/usr/local/lib/python3.9/dist-packages/mysql/connector/cursor.py", line 617, in execute
[Tue Feb 07 15:18:11.890915 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]     self._handle_result(self._connection.cmd_query(stmt))
[Tue Feb 07 15:18:11.890954 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]   File "/usr/local/lib/python3.9/dist-packages/mysql/connector/connection.py", line 1046, in cmd_query
[Tue Feb 07 15:18:11.890992 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]     result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
[Tue Feb 07 15:18:11.891037 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]   File "/usr/local/lib/python3.9/dist-packages/mysql/connector/connection.py", line 824, in _handle_result
[Tue Feb 07 15:18:11.891077 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517]     raise get_exception(packet)
[Tue Feb 07 15:18:11.891114 2023] [wsgi:error] [pid 4257:tid 548238025088] [remote 192.168.1.222:65517] mysql.connector.errors.DataError: 1406 (22001): Data too long for column 'moisture' at row 1
Warning: empty x range [1.67581e+09:1.67581e+09], adjusting to [1.65905e+09:1.69257e+09]
Warning: empty y range [555:555], adjusting to [549.45:560.55]
[Wed Feb 08 00:38:29.107826 2023] [wsgi:error] [pid 5408:tid 548111176064] [remote 192.168.1.222:49409] mod_wsgi (pid=5408): Failed to exec Python script file '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 08 00:38:29.108157 2023] [wsgi:error] [pid 5408:tid 548111176064] [remote 192.168.1.222:49409] mod_wsgi (pid=5408): Exception occurred processing WSGI script '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 08 00:38:29.124443 2023] [wsgi:error] [pid 5408:tid 548111176064] [remote 192.168.1.222:49409] Traceback (most recent call last):
[Wed Feb 08 00:38:29.124698 2023] [wsgi:error] [pid 5408:tid 548111176064] [remote 192.168.1.222:49409]   File "/var/www/basic-flask-app/app.wsgi", line 9, in <module>
[Wed Feb 08 00:38:29.124752 2023] [wsgi:error] [pid 5408:tid 548111176064] [remote 192.168.1.222:49409]     from app import app as application
[Wed Feb 08 00:38:29.124875 2023] [wsgi:error] [pid 5408:tid 548111176064] [remote 192.168.1.222:49409]   File "/var/www/basic-flask-app/app.py", line 111
[Wed Feb 08 00:38:29.124992 2023] [wsgi:error] [pid 5408:tid 548111176064] [remote 192.168.1.222:49409]     return render_template('main.html', result=num1)
[Wed Feb 08 00:38:29.125115 2023] [wsgi:error] [pid 5408:tid 548111176064] [remote 192.168.1.222:49409]     ^
[Wed Feb 08 00:38:29.125217 2023] [wsgi:error] [pid 5408:tid 548111176064] [remote 192.168.1.222:49409] SyntaxError: invalid syntax
[Wed Feb 08 00:39:35.760274 2023] [wsgi:error] [pid 5537:tid 548182077824] [remote 192.168.1.222:49410] [2023-02-08 00:39:35,757] ERROR in app: Exception on /generate [POST]
[Wed Feb 08 00:39:35.760386 2023] [wsgi:error] [pid 5537:tid 548182077824] [remote 192.168.1.222:49410] Traceback (most recent call last):
[Wed Feb 08 00:39:35.760401 2023] [wsgi:error] [pid 5537:tid 548182077824] [remote 192.168.1.222:49410]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
[Wed Feb 08 00:39:35.760415 2023] [wsgi:error] [pid 5537:tid 548182077824] [remote 192.168.1.222:49410]     response = self.full_dispatch_request()
[Wed Feb 08 00:39:35.760455 2023] [wsgi:error] [pid 5537:tid 548182077824] [remote 192.168.1.222:49410]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Wed Feb 08 00:39:35.760469 2023] [wsgi:error] [pid 5537:tid 548182077824] [remote 192.168.1.222:49410]     rv = self.handle_user_exception(e)
[Wed Feb 08 00:39:35.760482 2023] [wsgi:error] [pid 5537:tid 548182077824] [remote 192.168.1.222:49410]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Wed Feb 08 00:39:35.760495 2023] [wsgi:error] [pid 5537:tid 548182077824] [remote 192.168.1.222:49410]     rv = self.dispatch_request()
[Wed Feb 08 00:39:35.760508 2023] [wsgi:error] [pid 5537:tid 548182077824] [remote 192.168.1.222:49410]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
[Wed Feb 08 00:39:35.760521 2023] [wsgi:error] [pid 5537:tid 548182077824] [remote 192.168.1.222:49410]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Wed Feb 08 00:39:35.760534 2023] [wsgi:error] [pid 5537:tid 548182077824] [remote 192.168.1.222:49410]   File "/var/www/basic-flask-app/app.py", line 109, in generateDate
[Wed Feb 08 00:39:35.760548 2023] [wsgi:error] [pid 5537:tid 548182077824] [remote 192.168.1.222:49410]     os.system("gnuplot -p -e \\"set terminal png size 1500,1500; set output \\'/var/www/basic-flask-app/static/{num1}.png\\'; load \\'/var/www/basic-flask-app/gnuMoisturePlotScript\\'\\"".format(num1))
[Wed Feb 08 00:39:35.760561 2023] [wsgi:error] [pid 5537:tid 548182077824] [remote 192.168.1.222:49410] KeyError: 'num1'
[Wed Feb 08 00:51:00.837410 2023] [wsgi:error] [pid 6008:tid 548479803776] [remote 192.168.1.222:49425] mod_wsgi (pid=6008): Failed to exec Python script file '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 08 00:51:00.837733 2023] [wsgi:error] [pid 6008:tid 548479803776] [remote 192.168.1.222:49425] mod_wsgi (pid=6008): Exception occurred processing WSGI script '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 08 00:51:00.853495 2023] [wsgi:error] [pid 6008:tid 548479803776] [remote 192.168.1.222:49425] Traceback (most recent call last):
[Wed Feb 08 00:51:00.853748 2023] [wsgi:error] [pid 6008:tid 548479803776] [remote 192.168.1.222:49425]   File "/var/www/basic-flask-app/app.wsgi", line 9, in <module>
[Wed Feb 08 00:51:00.853802 2023] [wsgi:error] [pid 6008:tid 548479803776] [remote 192.168.1.222:49425]     from app import app as application
[Wed Feb 08 00:51:00.854017 2023] [wsgi:error] [pid 6008:tid 548479803776] [remote 192.168.1.222:49425]   File "/var/www/basic-flask-app/app.py", line 57
[Wed Feb 08 00:51:00.854146 2023] [wsgi:error] [pid 6008:tid 548479803776] [remote 192.168.1.222:49425]     os.remove(file) for file in os.listdir('/var/www/basic-flask-app/static') if file.endswith('.png')
[Wed Feb 08 00:51:00.854293 2023] [wsgi:error] [pid 6008:tid 548479803776] [remote 192.168.1.222:49425]                     ^
[Wed Feb 08 00:51:00.854396 2023] [wsgi:error] [pid 6008:tid 548479803776] [remote 192.168.1.222:49425] SyntaxError: invalid syntax
[Wed Feb 08 00:54:49.067104 2023] [wsgi:error] [pid 6138:tid 548172632448] [remote 192.168.1.222:49427] [2023-02-08 00:54:49,060] ERROR in app: Exception on /generate [POST]
[Wed Feb 08 00:54:49.067335 2023] [wsgi:error] [pid 6138:tid 548172632448] [remote 192.168.1.222:49427] Traceback (most recent call last):
[Wed Feb 08 00:54:49.067386 2023] [wsgi:error] [pid 6138:tid 548172632448] [remote 192.168.1.222:49427]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
[Wed Feb 08 00:54:49.067428 2023] [wsgi:error] [pid 6138:tid 548172632448] [remote 192.168.1.222:49427]     response = self.full_dispatch_request()
[Wed Feb 08 00:54:49.067474 2023] [wsgi:error] [pid 6138:tid 548172632448] [remote 192.168.1.222:49427]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Wed Feb 08 00:54:49.067572 2023] [wsgi:error] [pid 6138:tid 548172632448] [remote 192.168.1.222:49427]     rv = self.handle_user_exception(e)
[Wed Feb 08 00:54:49.067611 2023] [wsgi:error] [pid 6138:tid 548172632448] [remote 192.168.1.222:49427]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Wed Feb 08 00:54:49.067650 2023] [wsgi:error] [pid 6138:tid 548172632448] [remote 192.168.1.222:49427]     rv = self.dispatch_request()
[Wed Feb 08 00:54:49.067686 2023] [wsgi:error] [pid 6138:tid 548172632448] [remote 192.168.1.222:49427]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
[Wed Feb 08 00:54:49.067752 2023] [wsgi:error] [pid 6138:tid 548172632448] [remote 192.168.1.222:49427]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Wed Feb 08 00:54:49.067790 2023] [wsgi:error] [pid 6138:tid 548172632448] [remote 192.168.1.222:49427]   File "/var/www/basic-flask-app/app.py", line 59, in generateDate
[Wed Feb 08 00:54:49.067827 2023] [wsgi:error] [pid 6138:tid 548172632448] [remote 192.168.1.222:49427]     os.remove(file)
[Wed Feb 08 00:54:49.067863 2023] [wsgi:error] [pid 6138:tid 548172632448] [remote 192.168.1.222:49427] FileNotFoundError: [Errno 2] No such file or directory: '32310.png'
[Wed Feb 08 01:01:09.269147 2023] [wsgi:error] [pid 6590:tid 548049932672] [remote 192.168.1.222:49433] [2023-02-08 01:01:09,266] ERROR in app: Exception on /generate [POST]
[Wed Feb 08 01:01:09.269261 2023] [wsgi:error] [pid 6590:tid 548049932672] [remote 192.168.1.222:49433] Traceback (most recent call last):
[Wed Feb 08 01:01:09.269278 2023] [wsgi:error] [pid 6590:tid 548049932672] [remote 192.168.1.222:49433]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
[Wed Feb 08 01:01:09.269292 2023] [wsgi:error] [pid 6590:tid 548049932672] [remote 192.168.1.222:49433]     response = self.full_dispatch_request()
[Wed Feb 08 01:01:09.269308 2023] [wsgi:error] [pid 6590:tid 548049932672] [remote 192.168.1.222:49433]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Wed Feb 08 01:01:09.269322 2023] [wsgi:error] [pid 6590:tid 548049932672] [remote 192.168.1.222:49433]     rv = self.handle_user_exception(e)
[Wed Feb 08 01:01:09.269334 2023] [wsgi:error] [pid 6590:tid 548049932672] [remote 192.168.1.222:49433]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Wed Feb 08 01:01:09.269348 2023] [wsgi:error] [pid 6590:tid 548049932672] [remote 192.168.1.222:49433]     rv = self.dispatch_request()
[Wed Feb 08 01:01:09.269360 2023] [wsgi:error] [pid 6590:tid 548049932672] [remote 192.168.1.222:49433]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
[Wed Feb 08 01:01:09.269374 2023] [wsgi:error] [pid 6590:tid 548049932672] [remote 192.168.1.222:49433]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Wed Feb 08 01:01:09.269387 2023] [wsgi:error] [pid 6590:tid 548049932672] [remote 192.168.1.222:49433]   File "/var/www/basic-flask-app/app.py", line 91, in generateDate
[Wed Feb 08 01:01:09.269399 2023] [wsgi:error] [pid 6590:tid 548049932672] [remote 192.168.1.222:49433]     num1 = num1 + ".png"
[Wed Feb 08 01:01:09.269412 2023] [wsgi:error] [pid 6590:tid 548049932672] [remote 192.168.1.222:49433] TypeError: unsupported operand type(s) for +: 'int' and 'str'
[Wed Feb 08 01:04:49.348430 2023] [wsgi:error] [pid 6824:tid 548137468288] [remote 192.168.1.222:49449] mod_wsgi (pid=6824): Failed to exec Python script file '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 08 01:04:49.348632 2023] [wsgi:error] [pid 6824:tid 548137468288] [remote 192.168.1.222:49449] mod_wsgi (pid=6824): Exception occurred processing WSGI script '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 08 01:04:49.354897 2023] [wsgi:error] [pid 6824:tid 548137468288] [remote 192.168.1.222:49449] Traceback (most recent call last):
[Wed Feb 08 01:04:49.355015 2023] [wsgi:error] [pid 6824:tid 548137468288] [remote 192.168.1.222:49449]   File "/var/www/basic-flask-app/app.wsgi", line 9, in <module>
[Wed Feb 08 01:04:49.355034 2023] [wsgi:error] [pid 6824:tid 548137468288] [remote 192.168.1.222:49449]     from app import app as application
[Wed Feb 08 01:04:49.355077 2023] [wsgi:error] [pid 6824:tid 548137468288] [remote 192.168.1.222:49449]   File "/var/www/basic-flask-app/app.py", line 91
[Wed Feb 08 01:04:49.355117 2023] [wsgi:error] [pid 6824:tid 548137468288] [remote 192.168.1.222:49449]     num1 = "./static/"str(num1) + ".png"
[Wed Feb 08 01:04:49.355169 2023] [wsgi:error] [pid 6824:tid 548137468288] [remote 192.168.1.222:49449]                       ^
[Wed Feb 08 01:04:49.355203 2023] [wsgi:error] [pid 6824:tid 548137468288] [remote 192.168.1.222:49449] SyntaxError: invalid syntax

set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static/./static/2734142.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                      ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static/./static/4665794.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                      ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static/./static/2925581.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                      ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/4365597.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                     ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/1432717.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                     ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/4725341.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                     ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/3704099.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                     ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/4150239.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                     ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/610757.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                    ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/2873996.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                     ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/1677095.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                     ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/31218.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                   ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/1748600.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                     ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/1135723.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                     ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/521326.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                    ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/3091008.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                     ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/1389339.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                     ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/3579256.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                     ^
line 0: cannot open file; output not changed
system error: No such file or directory


set terminal png size 1500,1500; set output '/var/www/basic-flask-app/static//static/473946.png.png'; load '/var/www/basic-flask-app/gnuMoisturePlotScript'
                                                                                                    ^
line 0: cannot open file; output not changed
system error: No such file or directory

Warning: empty x range [1.67583e+09:1.67583e+09], adjusting to [1.65908e+09:1.69259e+09]
Warning: empty y range [17:17], adjusting to [16.83:17.17]
[Wed Feb 22 06:56:12.752691 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56784] mod_wsgi (pid=7818): Failed to exec Python script file '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 22 06:56:12.753149 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56784] mod_wsgi (pid=7818): Exception occurred processing WSGI script '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 22 06:56:12.769341 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56784] Traceback (most recent call last):
[Wed Feb 22 06:56:12.769589 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56784]   File "/var/www/basic-flask-app/app.wsgi", line 9, in <module>
[Wed Feb 22 06:56:12.769641 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56784]     from app import app as application
[Wed Feb 22 06:56:12.769763 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56784]   File "/var/www/basic-flask-app/app.py", line 141
[Wed Feb 22 06:56:12.769878 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56784]     connection= = databaseConnect()
[Wed Feb 22 06:56:12.770019 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56784]                 ^
[Wed Feb 22 06:56:12.770120 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56784] SyntaxError: invalid syntax
[Wed Feb 22 06:56:12.846941 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56785] mod_wsgi (pid=7818): Failed to exec Python script file '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 22 06:56:12.847087 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56785] mod_wsgi (pid=7818): Exception occurred processing WSGI script '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 22 06:56:12.847314 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56785] Traceback (most recent call last):
[Wed Feb 22 06:56:12.847391 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56785]   File "/var/www/basic-flask-app/app.wsgi", line 9, in <module>
[Wed Feb 22 06:56:12.847409 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56785]     from app import app as application
[Wed Feb 22 06:56:12.847455 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56785]   File "/var/www/basic-flask-app/app.py", line 141
[Wed Feb 22 06:56:12.847494 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56785]     connection= = databaseConnect()
[Wed Feb 22 06:56:12.847549 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56785]                 ^
[Wed Feb 22 06:56:12.847583 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56785] SyntaxError: invalid syntax
[Wed Feb 22 06:56:18.267087 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56807] mod_wsgi (pid=7818): Failed to exec Python script file '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 22 06:56:18.267383 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56807] mod_wsgi (pid=7818): Exception occurred processing WSGI script '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 22 06:56:18.269259 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56807] Traceback (most recent call last):
[Wed Feb 22 06:56:18.269457 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56807]   File "/var/www/basic-flask-app/app.wsgi", line 9, in <module>
[Wed Feb 22 06:56:18.269509 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56807]     from app import app as application
[Wed Feb 22 06:56:18.269632 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56807]   File "/var/www/basic-flask-app/app.py", line 141
[Wed Feb 22 06:56:18.269747 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56807]     connection= = databaseConnect()
[Wed Feb 22 06:56:18.269901 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56807]                 ^
[Wed Feb 22 06:56:18.270004 2023] [wsgi:error] [pid 7818:tid 547895517568] [remote 192.168.1.222:56807] SyntaxError: invalid syntax
[Wed Feb 22 06:56:18.351500 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56808] mod_wsgi (pid=7818): Failed to exec Python script file '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 22 06:56:18.351759 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56808] mod_wsgi (pid=7818): Exception occurred processing WSGI script '/var/www/basic-flask-app/app.wsgi'.
[Wed Feb 22 06:56:18.352134 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56808] Traceback (most recent call last):
[Wed Feb 22 06:56:18.352267 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56808]   File "/var/www/basic-flask-app/app.wsgi", line 9, in <module>
[Wed Feb 22 06:56:18.352305 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56808]     from app import app as application
[Wed Feb 22 06:56:18.352400 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56808]   File "/var/www/basic-flask-app/app.py", line 141
[Wed Feb 22 06:56:18.352486 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56808]     connection= = databaseConnect()
[Wed Feb 22 06:56:18.352600 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56808]                 ^
[Wed Feb 22 06:56:18.352677 2023] [wsgi:error] [pid 7818:tid 547861946752] [remote 192.168.1.222:56808] SyntaxError: invalid syntax
[Mon Feb 27 01:14:25.516805 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518] [2023-02-27 01:14:25,510] ERROR in app: Exception on /generate [POST]
[Mon Feb 27 01:14:25.516917 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518] Traceback (most recent call last):
[Mon Feb 27 01:14:25.516932 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
[Mon Feb 27 01:14:25.516946 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518]     response = self.full_dispatch_request()
[Mon Feb 27 01:14:25.516961 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Mon Feb 27 01:14:25.516975 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518]     rv = self.handle_user_exception(e)
[Mon Feb 27 01:14:25.516988 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Mon Feb 27 01:14:25.517001 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518]     rv = self.dispatch_request()
[Mon Feb 27 01:14:25.517013 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
[Mon Feb 27 01:14:25.517026 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Mon Feb 27 01:14:25.517039 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518]   File "/var/www/basic-flask-app/app.py", line 137, in generateDate
[Mon Feb 27 01:14:25.517052 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518]     num1 = pullGraph("select * from  garden.soilMoisture")
[Mon Feb 27 01:14:25.517064 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518]   File "/var/www/basic-flask-app/app.py", line 25, in pullGraph
[Mon Feb 27 01:14:25.517076 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518]     create_cursor = connection.cursor()
[Mon Feb 27 01:14:25.517089 2023] [wsgi:error] [pid 15163:tid 548197028224] [remote 192.168.1.222:51518] NameError: name 'connection' is not defined
[Mon Feb 27 01:19:53.381725 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546] [2023-02-27 01:19:53,379] ERROR in app: Exception on /generate [POST]
[Mon Feb 27 01:19:53.381867 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546] Traceback (most recent call last):
[Mon Feb 27 01:19:53.381883 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
[Mon Feb 27 01:19:53.381897 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546]     response = self.full_dispatch_request()
[Mon Feb 27 01:19:53.381914 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Mon Feb 27 01:19:53.381928 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546]     rv = self.handle_user_exception(e)
[Mon Feb 27 01:19:53.381941 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Mon Feb 27 01:19:53.381954 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546]     rv = self.dispatch_request()
[Mon Feb 27 01:19:53.381967 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
[Mon Feb 27 01:19:53.381981 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Mon Feb 27 01:19:53.381994 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546]   File "/var/www/basic-flask-app/app.py", line 138, in generateDate
[Mon Feb 27 01:19:53.382007 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546]     num1 = pullGraph("select * from  garden.soilMoisture",connection)
[Mon Feb 27 01:19:53.382020 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546]   File "/var/www/basic-flask-app/app.py", line 72, in pullGraph
[Mon Feb 27 01:19:53.382033 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546]     return none
[Mon Feb 27 01:19:53.382046 2023] [wsgi:error] [pid 15430:tid 548202602880] [remote 192.168.1.222:51546] NameError: name 'none' is not defined
[Mon Feb 27 01:35:29.679997 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560] [2023-02-27 01:35:29,665] ERROR in app: Exception on /generateDate [POST]
[Mon Feb 27 01:35:29.680215 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560] Traceback (most recent call last):
[Mon Feb 27 01:35:29.680261 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
[Mon Feb 27 01:35:29.680304 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]     response = self.full_dispatch_request()
[Mon Feb 27 01:35:29.680415 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Mon Feb 27 01:35:29.680458 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]     rv = self.handle_user_exception(e)
[Mon Feb 27 01:35:29.680497 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Mon Feb 27 01:35:29.680538 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]     rv = self.dispatch_request()
[Mon Feb 27 01:35:29.680640 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
[Mon Feb 27 01:35:29.680683 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Mon Feb 27 01:35:29.680722 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]   File "/var/www/basic-flask-app/app.py", line 163, in generateDateData
[Mon Feb 27 01:35:29.680761 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]     num1 = pullGraph("select * from garden.soilMoisture where cast(dateTime as date)=date\\"{}\\"".format(request.form['date']),connection)
[Mon Feb 27 01:35:29.680802 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]   File "/var/www/basic-flask-app/app.py", line 27, in pullGraph
[Mon Feb 27 01:35:29.680840 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]     create_cursor.execute(gardenDataInsert)
[Mon Feb 27 01:35:29.680878 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]   File "/usr/local/lib/python3.9/dist-packages/mysql/connector/cursor.py", line 617, in execute
[Mon Feb 27 01:35:29.680917 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]     self._handle_result(self._connection.cmd_query(stmt))
[Mon Feb 27 01:35:29.680955 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]   File "/usr/local/lib/python3.9/dist-packages/mysql/connector/connection.py", line 1046, in cmd_query
[Mon Feb 27 01:35:29.680995 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]     result = self._handle_result(self._send_cmd(ServerCmd.QUERY, query))
[Mon Feb 27 01:35:29.681035 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]   File "/usr/local/lib/python3.9/dist-packages/mysql/connector/connection.py", line 824, in _handle_result
[Mon Feb 27 01:35:29.681074 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560]     raise get_exception(packet)
[Mon Feb 27 01:35:29.681112 2023] [wsgi:error] [pid 15976:tid 547920699776] [remote 192.168.1.222:51560] mysql.connector.errors.DatabaseError: 1525 (HY000): Incorrect DATE value: ''
[Mon Feb 27 01:40:22.566444 2023] [wsgi:error] [pid 16094:tid 547983860096] [remote 192.168.1.222:51564] [2023-02-27 01:40:22,564] ERROR in app: Exception on /generateDate [POST]
[Mon Feb 27 01:40:22.566555 2023] [wsgi:error] [pid 16094:tid 547983860096] [remote 192.168.1.222:51564] Traceback (most recent call last):
[Mon Feb 27 01:40:22.566571 2023] [wsgi:error] [pid 16094:tid 547983860096] [remote 192.168.1.222:51564]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
[Mon Feb 27 01:40:22.566585 2023] [wsgi:error] [pid 16094:tid 547983860096] [remote 192.168.1.222:51564]     response = self.full_dispatch_request()
[Mon Feb 27 01:40:22.566599 2023] [wsgi:error] [pid 16094:tid 547983860096] [remote 192.168.1.222:51564]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Mon Feb 27 01:40:22.566612 2023] [wsgi:error] [pid 16094:tid 547983860096] [remote 192.168.1.222:51564]     rv = self.handle_user_exception(e)
[Mon Feb 27 01:40:22.566625 2023] [wsgi:error] [pid 16094:tid 547983860096] [remote 192.168.1.222:51564]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Mon Feb 27 01:40:22.566639 2023] [wsgi:error] [pid 16094:tid 547983860096] [remote 192.168.1.222:51564]     rv = self.dispatch_request()
[Mon Feb 27 01:40:22.566652 2023] [wsgi:error] [pid 16094:tid 547983860096] [remote 192.168.1.222:51564]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
[Mon Feb 27 01:40:22.566696 2023] [wsgi:error] [pid 16094:tid 547983860096] [remote 192.168.1.222:51564]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Mon Feb 27 01:40:22.566710 2023] [wsgi:error] [pid 16094:tid 547983860096] [remote 192.168.1.222:51564]   File "/var/www/basic-flask-app/app.py", line 170, in generateDateData
[Mon Feb 27 01:40:22.566723 2023] [wsgi:error] [pid 16094:tid 547983860096] [remote 192.168.1.222:51564]     num1 = "/static/" + str(num1) + ".png"
[Mon Feb 27 01:40:22.566736 2023] [wsgi:error] [pid 16094:tid 547983860096] [remote 192.168.1.222:51564] UnboundLocalError: local variable 'num1' referenced before assignment
[Fri Mar 03 05:34:49.230284 2023] [wsgi:error] [pid 23659:tid 547565687168] [remote 192.168.1.222:63486] mod_wsgi (pid=23659): Failed to exec Python script file '/var/www/basic-flask-app/app.wsgi'.
[Fri Mar 03 05:34:49.230622 2023] [wsgi:error] [pid 23659:tid 547565687168] [remote 192.168.1.222:63486] mod_wsgi (pid=23659): Exception occurred processing WSGI script '/var/www/basic-flask-app/app.wsgi'.
[Fri Mar 03 05:34:49.246645 2023] [wsgi:error] [pid 23659:tid 547565687168] [remote 192.168.1.222:63486] Traceback (most recent call last):
[Fri Mar 03 05:34:49.246893 2023] [wsgi:error] [pid 23659:tid 547565687168] [remote 192.168.1.222:63486]   File "/var/www/basic-flask-app/app.wsgi", line 9, in <module>
[Fri Mar 03 05:34:49.246946 2023] [wsgi:error] [pid 23659:tid 547565687168] [remote 192.168.1.222:63486]     from app import app as application
[Fri Mar 03 05:34:49.247068 2023] [wsgi:error] [pid 23659:tid 547565687168] [remote 192.168.1.222:63486]   File "/var/www/basic-flask-app/app.py", line 185
[Fri Mar 03 05:34:49.247184 2023] [wsgi:error] [pid 23659:tid 547565687168] [remote 192.168.1.222:63486]     if (request.form['dateTwo'] != '') && (request.form['dateThree'] != ''):
[Fri Mar 03 05:34:49.247348 2023] [wsgi:error] [pid 23659:tid 547565687168] [remote 192.168.1.222:63486]                                         ^
[Fri Mar 03 05:34:49.247448 2023] [wsgi:error] [pid 23659:tid 547565687168] [remote 192.168.1.222:63486] SyntaxError: invalid syntax
[Fri Mar 03 05:34:49.344496 2023] [wsgi:error] [pid 23659:tid 547532116352] [remote 192.168.1.222:63487] mod_wsgi (pid=23659): Failed to exec Python script file '/var/www/basic-flask-app/app.wsgi'.
[Fri Mar 03 05:34:49.344644 2023] [wsgi:error] [pid 23659:tid 547532116352] [remote 192.168.1.222:63487] mod_wsgi (pid=23659): Exception occurred processing WSGI script '/var/www/basic-flask-app/app.wsgi'.
[Fri Mar 03 05:34:49.344876 2023] [wsgi:error] [pid 23659:tid 547532116352] [remote 192.168.1.222:63487] Traceback (most recent call last):
[Fri Mar 03 05:34:49.344948 2023] [wsgi:error] [pid 23659:tid 547532116352] [remote 192.168.1.222:63487]   File "/var/www/basic-flask-app/app.wsgi", line 9, in <module>
[Fri Mar 03 05:34:49.344966 2023] [wsgi:error] [pid 23659:tid 547532116352] [remote 192.168.1.222:63487]     from app import app as application
[Fri Mar 03 05:34:49.345011 2023] [wsgi:error] [pid 23659:tid 547532116352] [remote 192.168.1.222:63487]   File "/var/www/basic-flask-app/app.py", line 185
[Fri Mar 03 05:34:49.345053 2023] [wsgi:error] [pid 23659:tid 547532116352] [remote 192.168.1.222:63487]     if (request.form['dateTwo'] != '') && (request.form['dateThree'] != ''):
[Fri Mar 03 05:34:49.345117 2023] [wsgi:error] [pid 23659:tid 547532116352] [remote 192.168.1.222:63487]                                         ^
[Fri Mar 03 05:34:49.345151 2023] [wsgi:error] [pid 23659:tid 547532116352] [remote 192.168.1.222:63487] SyntaxError: invalid syntax
Warning: empty y range [0:0], adjusting to [-1:1]
Warning: empty x range [1.67792e+09:1.67792e+09], adjusting to [1.66114e+09:1.6947e+09]
Warning: empty y range [237:237], adjusting to [234.63:239.37]
Warning: empty x range [1.67792e+09:1.67792e+09], adjusting to [1.66114e+09:1.6947e+09]
Warning: empty y range [237:237], adjusting to [234.63:239.37]
Warning: empty x range [1.67792e+09:1.67792e+09], adjusting to [1.66114e+09:1.6947e+09]
Warning: empty y range [237:237], adjusting to [234.63:239.37]
Warning: empty x range [1.67792e+09:1.67792e+09], adjusting to [1.66114e+09:1.6947e+09]
Warning: empty y range [237:237], adjusting to [234.63:239.37]
Warning: empty x range [1.67792e+09:1.67792e+09], adjusting to [1.66114e+09:1.6947e+09]
Warning: empty y range [237:237], adjusting to [234.63:239.37]
Warning: empty x range [1.67792e+09:1.67792e+09], adjusting to [1.66114e+09:1.6947e+09]
Warning: empty y range [237:237], adjusting to [234.63:239.37]
Warning: empty y range [237:237], adjusting to [234.63:239.37]
Warning: empty y range [237:237], adjusting to [234.63:239.37]
Warning: empty y range [237:237], adjusting to [234.63:239.37]
[Sun Mar 05 06:03:54.286347 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922] [2023-03-05 06:03:54,279] ERROR in app: Exception on /form [POST]
[Sun Mar 05 06:03:54.286466 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922] Traceback (most recent call last):
[Sun Mar 05 06:03:54.286482 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
[Sun Mar 05 06:03:54.286495 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]     response = self.full_dispatch_request()
[Sun Mar 05 06:03:54.286512 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Sun Mar 05 06:03:54.286525 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]     rv = self.handle_user_exception(e)
[Sun Mar 05 06:03:54.286538 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Sun Mar 05 06:03:54.286551 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]     rv = self.dispatch_request()
[Sun Mar 05 06:03:54.286563 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
[Sun Mar 05 06:03:54.286576 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Sun Mar 05 06:03:54.286588 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]   File "/var/www/basic-flask-app/app.py", line 232, in form
[Sun Mar 05 06:03:54.286601 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]     return render_template('main.html', result = session["user"])
[Sun Mar 05 06:03:54.286613 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
[Sun Mar 05 06:03:54.286626 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]     return _render(app, template, context)
[Sun Mar 05 06:03:54.286638 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
[Sun Mar 05 06:03:54.286651 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]     rv = template.render(context)
[Sun Mar 05 06:03:54.286663 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
[Sun Mar 05 06:03:54.286698 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]     self.environment.handle_exception()
[Sun Mar 05 06:03:54.286711 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
[Sun Mar 05 06:03:54.286724 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]     raise rewrite_traceback_stack(source=source)
[Sun Mar 05 06:03:54.286736 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]   File "/var/www/basic-flask-app/templates/main.html", line 84, in top-level template code
[Sun Mar 05 06:03:54.286748 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922]     {% if result is None %}
[Sun Mar 05 06:03:54.286760 2023] [wsgi:error] [pid 31025:tid 548363243904] [remote 192.168.1.158:62922] jinja2.exceptions.TemplateRuntimeError: No test named 'None' found.
[Sun Mar 05 06:04:03.377693 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927] [2023-03-05 06:04:03,372] ERROR in app: Exception on /form [POST]
[Sun Mar 05 06:04:03.377848 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927] Traceback (most recent call last):
[Sun Mar 05 06:04:03.377893 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
[Sun Mar 05 06:04:03.377935 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]     response = self.full_dispatch_request()
[Sun Mar 05 06:04:03.377975 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Sun Mar 05 06:04:03.378016 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]     rv = self.handle_user_exception(e)
[Sun Mar 05 06:04:03.378052 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Sun Mar 05 06:04:03.378090 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]     rv = self.dispatch_request()
[Sun Mar 05 06:04:03.378127 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
[Sun Mar 05 06:04:03.378166 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Sun Mar 05 06:04:03.378204 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]   File "/var/www/basic-flask-app/app.py", line 232, in form
[Sun Mar 05 06:04:03.378241 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]     return render_template('main.html', result = session["user"])
[Sun Mar 05 06:04:03.378279 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/templating.py", line 147, in render_template
[Sun Mar 05 06:04:03.378317 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]     return _render(app, template, context)
[Sun Mar 05 06:04:03.378354 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/templating.py", line 130, in _render
[Sun Mar 05 06:04:03.378392 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]     rv = template.render(context)
[Sun Mar 05 06:04:03.378490 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
[Sun Mar 05 06:04:03.378531 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]     self.environment.handle_exception()
[Sun Mar 05 06:04:03.378570 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
[Sun Mar 05 06:04:03.378608 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]     raise rewrite_traceback_stack(source=source)
[Sun Mar 05 06:04:03.378645 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]   File "/var/www/basic-flask-app/templates/main.html", line 84, in top-level template code
[Sun Mar 05 06:04:03.378682 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927]     {% if result is None %}
[Sun Mar 05 06:04:03.378718 2023] [wsgi:error] [pid 31025:tid 548329673088] [remote 192.168.1.158:62927] jinja2.exceptions.TemplateRuntimeError: No test named 'None' found.
[Sun Mar 05 06:21:18.847223 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.158:63401] mod_wsgi (pid=31690): Failed to exec Python script file '/var/www/basic-flask-app/app.wsgi'.
[Sun Mar 05 06:21:18.847391 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.158:63401] mod_wsgi (pid=31690): Exception occurred processing WSGI script '/var/www/basic-flask-app/app.wsgi'.
[Sun Mar 05 06:21:18.853698 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.158:63401] Traceback (most recent call last):
[Sun Mar 05 06:21:18.853819 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.158:63401]   File "/var/www/basic-flask-app/app.wsgi", line 9, in <module>
[Sun Mar 05 06:21:18.853838 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.158:63401]     from app import app as application
[Sun Mar 05 06:21:18.853882 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.158:63401]   File "/var/www/basic-flask-app/app.py", line 141
[Sun Mar 05 06:21:18.853922 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.158:63401]     if num1 not None:
[Sun Mar 05 06:21:18.853973 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.158:63401]                 ^
[Sun Mar 05 06:21:18.854007 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.158:63401] SyntaxError: invalid syntax
[Sun Mar 05 06:21:18.910321 2023] [wsgi:error] [pid 31690:tid 547884286336] [remote 192.168.1.158:63402] mod_wsgi (pid=31690): Failed to exec Python script file '/var/www/basic-flask-app/app.wsgi'.
[Sun Mar 05 06:21:18.910462 2023] [wsgi:error] [pid 31690:tid 547884286336] [remote 192.168.1.158:63402] mod_wsgi (pid=31690): Exception occurred processing WSGI script '/var/www/basic-flask-app/app.wsgi'.
[Sun Mar 05 06:21:18.910686 2023] [wsgi:error] [pid 31690:tid 547884286336] [remote 192.168.1.158:63402] Traceback (most recent call last):
[Sun Mar 05 06:21:18.910762 2023] [wsgi:error] [pid 31690:tid 547884286336] [remote 192.168.1.158:63402]   File "/var/www/basic-flask-app/app.wsgi", line 9, in <module>
[Sun Mar 05 06:21:18.910779 2023] [wsgi:error] [pid 31690:tid 547884286336] [remote 192.168.1.158:63402]     from app import app as application
[Sun Mar 05 06:21:18.910824 2023] [wsgi:error] [pid 31690:tid 547884286336] [remote 192.168.1.158:63402]   File "/var/www/basic-flask-app/app.py", line 141
[Sun Mar 05 06:21:18.910866 2023] [wsgi:error] [pid 31690:tid 547884286336] [remote 192.168.1.158:63402]     if num1 not None:
[Sun Mar 05 06:21:18.910919 2023] [wsgi:error] [pid 31690:tid 547884286336] [remote 192.168.1.158:63402]                 ^
[Sun Mar 05 06:21:18.910953 2023] [wsgi:error] [pid 31690:tid 547884286336] [remote 192.168.1.158:63402] SyntaxError: invalid syntax
[Sun Mar 05 06:21:57.614392 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.184:53096] mod_wsgi (pid=31690): Failed to exec Python script file '/var/www/basic-flask-app/app.wsgi'.
[Sun Mar 05 06:21:57.614688 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.184:53096] mod_wsgi (pid=31690): Exception occurred processing WSGI script '/var/www/basic-flask-app/app.wsgi'.
[Sun Mar 05 06:21:57.615168 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.184:53096] Traceback (most recent call last):
[Sun Mar 05 06:21:57.615341 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.184:53096]   File "/var/www/basic-flask-app/app.wsgi", line 9, in <module>
[Sun Mar 05 06:21:57.615394 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.184:53096]     from app import app as application
[Sun Mar 05 06:21:57.615520 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.184:53096]   File "/var/www/basic-flask-app/app.py", line 141
[Sun Mar 05 06:21:57.615635 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.184:53096]     if num1 not None:
[Sun Mar 05 06:21:57.615780 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.184:53096]                 ^
[Sun Mar 05 06:21:57.615881 2023] [wsgi:error] [pid 31690:tid 547917857152] [remote 192.168.1.184:53096] SyntaxError: invalid syntax
[Sun Mar 05 06:26:15.721746 2023] [wsgi:error] [pid 31826:tid 548613218688] [remote 192.168.1.158:63585] [2023-03-05 06:26:15,719] ERROR in app: Exception on /generateDate [POST]
[Sun Mar 05 06:26:15.721856 2023] [wsgi:error] [pid 31826:tid 548613218688] [remote 192.168.1.158:63585] Traceback (most recent call last):
[Sun Mar 05 06:26:15.721871 2023] [wsgi:error] [pid 31826:tid 548613218688] [remote 192.168.1.158:63585]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
[Sun Mar 05 06:26:15.721885 2023] [wsgi:error] [pid 31826:tid 548613218688] [remote 192.168.1.158:63585]     response = self.full_dispatch_request()
[Sun Mar 05 06:26:15.721898 2023] [wsgi:error] [pid 31826:tid 548613218688] [remote 192.168.1.158:63585]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
[Sun Mar 05 06:26:15.721911 2023] [wsgi:error] [pid 31826:tid 548613218688] [remote 192.168.1.158:63585]     rv = self.handle_user_exception(e)
[Sun Mar 05 06:26:15.721924 2023] [wsgi:error] [pid 31826:tid 548613218688] [remote 192.168.1.158:63585]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
[Sun Mar 05 06:26:15.721937 2023] [wsgi:error] [pid 31826:tid 548613218688] [remote 192.168.1.158:63585]     rv = self.dispatch_request()
[Sun Mar 05 06:26:15.721950 2023] [wsgi:error] [pid 31826:tid 548613218688] [remote 192.168.1.158:63585]   File "/home/harry/.local/share/virtualenvs/basic-flask-app-2sD0MLz9/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
[Sun Mar 05 06:26:15.721963 2023] [wsgi:error] [pid 31826:tid 548613218688] [remote 192.168.1.158:63585]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
[Sun Mar 05 06:26:15.721976 2023] [wsgi:error] [pid 31826:tid 548613218688] [remote 192.168.1.158:63585]   File "/var/www/basic-flask-app/app.py", line 169, in generateDateData
[Sun Mar 05 06:26:15.721989 2023] [wsgi:error] [pid 31826:tid 548613218688] [remote 192.168.1.158:63585]     if num1 is not None:
[Sun Mar 05 06:26:15.722001 2023] [wsgi:error] [pid 31826:tid 548613218688] [remote 192.168.1.158:63585] UnboundLocalError: local variable 'num1' referenced before assignment
